### ISSUE TITLE
plot.y .has_key deprecated, change to in

### ISSUE THREAD

**Issue by DCSnip3r** [VROOM-Project/vroom-scripts#15]
Lines 23 and 89 of plot.py should be changed to use 'in' since has_key is deprecated with Python 3.x

Ref: https://stackoverflow.com/questions/1323410/should-i-use-has-key-or-in-on-python-dicts

Solution:
23:`  if(not 'routes' in solution):`
89:  `  if('routing' in solution['summary']['computing_times']):`

**Comment by jcoupey** [comment]
Thanks for pointing this out. PR for this kind of enhancements are always welcome!
