### ISSUE TITLE
Using Minimize Completion Time via Docker/ API Calls

### ISSUE THREAD

**Issue by dvortsis** [VROOM-Project/vroom-scripts#35]
Dear @jcoupey , 

Thank you so much for working on #31 . This is extremely helpful for what I've been attempting to accomplish! 

Pardon my question but I'm a noob when it comes to all this and I desperately want to utilize your solution. I'm using vroom in a docker container, which receives HTTP API requests. How would I incorporate this script into such a configuration?

**Comment by SirTypesALot** [comment]
Hi, I'm trying to find the index file you have aforementioned in the vroom docker folder, however I'm failing to do so. Could you maybe tell me where would I be able to find the file a bit more specific? Thanks

**Comment by jcoupey** [comment]
@SirTypesALot fetching the `vroom-express` stuff happens here in the Dockerfile https://github.com/VROOM-Project/vroom-docker/blob/de87a26c5ee0eae89ffc486741106b0e40505c56/Dockerfile#L28-L38 so there should be a `vroom-express` folder somewhere, containing the `src/index.js` file.
