### ISSUE TITLE
Possibility of adding negative time window constraint

### ISSUE THREAD

**Issue by SirTypesALot** [VROOM-Project/vroom-scripts#37]
Hi there,

I've been experimenting with the asap.py file for minimizing the completion time for a group of jobs to be serviced around a city.

My current use case is to optimize the routes on the fly as jobs has being created already before the optimization call, and I was wondering if there could be a possibility to also allow negative time constraint strictly to indicate how long ago was a job already available to be serviced. Doing this, would make a lot of sense when it comes to minimizing the job completion time no?

**Comment by jcoupey** [comment]
Using 0 as the beginning of the planning horizon is a formal convention. If you're stuck with that, it would be much simpler to simply change the planning horizon on your side. For example if you use real timestamps you can describe any time/date in a convenient way.

**Comment by SirTypesALot** [comment]
Hi, yes of course! Sorry, I've been working non stop for this past few days and totally forgot about converting it to epoch time.

Thanks!
