### ISSUE TITLE
Same job completion time with different profiles

### ISSUE THREAD

**Issue by SirTypesALot** [VROOM-Project/vroom-scripts#38]
I've recently discovered that the jobs completion time are equivalent when using profiles of `cycling-electric` and `cycling-regular` from ORS, is there any explanation as to why it is? Because I highly doubt that this two profiles would be traveling at the same speed or same roads.

**Comment by jcoupey** [comment]
This sounds out of scope for VROOM as we're only consuming the matrices from ORS. If the matrices are identical, you'll get identical results, but that's something you want to check outside optimization. You should really debug this at ORS level: look at ORS logs for requests from `vroom`, compare responses etc.

**Comment by SirTypesALot** [comment]
I've checked against the matrix output from the ORS, and it does shows different duration and distance values between all of the cycling profiles. The same story when comparing against ORS's own apis.

I've also checked ORS's log, and there were no errors being raised.

**Comment by jcoupey** [comment]
Are you sure requests are sent to the relevant endpoint/profile based on your VROOM input? You need to specify this through the `profile` key for vehicles.

What you can do is use [this script](https://github.com/VROOM-Project/vroom-scripts/blob/master/src/add_ors_matrix.py) to create a standalone problem with embedded matrix. You can then share the two instances you get with different profiles (only the matrices should differ).

**Comment by jcoupey** [comment]
Closing as stale.
