### ISSUE TITLE
Plot.py fails on Aamzon AMI Linux

### ISSUE THREAD

**Issue by gitbitlit** [VROOM-Project/vroom-scripts#5]
tried changing
backend      : TkAgg -->backend : agg

in /usr/local/lib64/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc file to compensate for AWS headless environment.

Traceback (most recent call last):
  File "plot.py", line 100, in <module>
    plot_routes(f)
  File "plot.py", line 26, in plot_routes
    xmin = solution['routes'][0]['steps'][0]['location'][0]
KeyError: 'location'

**Comment by jcoupey** [comment]
> KeyError: 'location'

Looks like the first step coordinates are missing in the solution file. Are you maybe using a custom matrix without supplying coordinates in input?

**Comment by gitbitlit** [comment]
sorry to grab your time! you are right.
The actual issue is related to matplotlib on Amazon Linux. That was fixed by changing matplotlibrc file.

my mistake : i tested plotting using sample solution from API docs that didn't have location data.

Thank you.
